baseURL = 'http://erykor.github.io/'
languageCode = 'en-us'
title = "Erykor's Blog"
theme = "paper"
publishDir = "docs"

[params]
  avatar = 'https://github.com/Erykor/erykor.github.io/blob/bf0c8d7fe62b76fc8a8e33f34f1c49bd2aca03d9/assets/avacoda.png?raw=true'
  name = 'Erykor'
  bio = 'A machine learning practitioner, blogging with GPT4.'