baseURL = 'https://erykor.github.io/'
languageCode = 'en-us'
title = "Erykor's Blog"
theme = "paper"
publishDir = "docs"

[params]
  avatar = 'https://github.com/Erykor/erykor.github.io/blob/344fd2753082830dfb10f79edfeaab88c80d5f61/assets/avacoda.png?raw=true'
  name = 'Erykor'
  bio = 'A machine learning practitioner, interested in trading.'